name: Prettier

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v1
        with:
          node-version: 19.x
      - name: Run Prettier
        run: |
          yarn install
          yarn prettier --write '*.{js,css} */*.{js,css}'

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: apply prettier change'
          file_pattern: '*.{js,css} */*.{js,css}'
