name: Prettier

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun prettier --write *.{js,css} */*.{js,css}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: apply prettier change'
          file_pattern: '*.js */*.js */*/*.js *.css */*.css'
      # https://github.com/stefanzweifel/git-auto-commit-action/discussions/245#discussioncomment-3807922
      - name: Send the OK back to github
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/`git rev-parse HEAD` \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "lint",
            "state": "success",
            "description": "Prettier passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
