name: Prettier

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun prettier --write *.{js,css} */*.{js,css} */*/*.js

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: apply prettier change'
          file_pattern: '*.js */*.js */*/*.js *.css */*.css'
